tests

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -1,65 +1,71 @@
 pipeline {
-    agent any
-    environment {
-        API_URL  = 'http://localhost:800/api/v2'
-        MQTT_URL = 'tcp://localhost:3883'
-    }
-    options {
-        skipDefaultCheckout true
-    }
-    stages {
-        stage('Prepare') {
-            steps {
-                sh 'sudo rm -fr data/*'
-                checkout scm
-                sh 'sudo chmod 777 data/* -R'
-                sh 'docker-compose pull'
-                dir("tests") {
-                   sh 'npm install'
-                }
-            }
+  agent any
+  environment {
+    API_URL  = 'http://localhost:800/api/v2'
+    MQTT_URL = 'tcp://localhost:3883'
+  }
+  options {
+    skipDefaultCheckout true
+  }
+  stages {
+    stage('Prepare') {
+      steps {
+        sh 'sudo rm -fr data/*'
+        checkout scm
+        sh 'sudo chmod 777 data/* -R'
+        sh 'docker-compose pull'
+        dir("tests") {
+           sh 'npm install'
         }
-        stage('Run') {
-            steps {
-                sh 'docker-compose -f docker-compose.yml -f docker-compose-first-run.yml up > log_platform.txt &'
-                timeout(5) {
-                     waitUntil {
-                         sh 'wget --retry-connrefused --tries=120 --waitretry=1 -q http://localhost:800/api/v2/devices -O /dev/null'
-                     }
-                }
+      }
+    }
+    stage('Run') {
+      steps {
+        sh 'docker-compose -f docker-compose.yml -f docker-compose-first-run.yml up > log_platform.txt &'
+        timeout(5) {
+          waitUntil {
+            sh 'wget --retry-connrefused --tries=120 --waitretry=1 -q http://localhost:800/api/v2/devices -O /dev/null'
 
+            try {
+              sh 'wget -q http://localhost:800/api/v2/devices -O /dev/null'
+              return true
+            } catch (exception) {
+              return false
             }
+          }
         }
-        stage('Test') {
-            steps {
-                dir("tests") {
-                   sh 'npm install'
-                   sh 'npm test 2>&1 > log.txt'
-                   sh 'exit_code=$?'
-                }
-            }
-        }
-        stage('Finalize') {
-            steps {
-                   sh 'docker-compose down'
-                   sh 'cat tests/log.txt'
-                   sh 'exit $exit_code'
-            }
-        }
+      }
     }
-    post {
-        success {
-            echo 'Success!'
+    stage('Test') {
+      steps {
+        dir("tests") {
+          sh 'npm install'
+          sh 'npm test 2>&1 > log.txt'
+          sh 'exit_code=$?'
         }
-        failure {
-            echo 'Failure!'
-        }
-        unstable {
-            echo 'This will run only if the run was marked as unstable'
-        }
-        changed {
-            echo 'This will run only if the state of the Pipeline has changed'
-            echo 'For example, if the Pipeline was previously failing but is now successful'
-        }
+      }
     }
+    stage('Finalize') {
+      steps {
+        sh 'docker-compose down'
+        sh 'cat tests/log.txt'
+        sh 'exit $exit_code'
+      }
+    }
+  }
+  post {
+    success {
+      echo 'Success!'
+    }
+    failure {
+      echo 'Failure!'
+    }
+    unstable {
+      echo 'This will run only if the run was marked as unstable'
+    }
+    changed {
+      echo 'This will run only if the state of the Pipeline has changed'
+      echo 'For example, if the Pipeline was previously failing but is now successful'
+    }
+  }
 }
